apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dbaasconnections.dbaas.redhat.com
  annotations:
    service.binding/credentials: 'path={.status.credentialsRef},objectType=Secret'
    service.binding/configuration: 'path={.status.connectionInfo},objectType=ConfigMap'
